### PR TITLE
Add version 4.12.0 changes into the trunk (some was already translated, I removed them)

### PR DESCRIPTION
**Pull request by mamarmite**
Keep any line :)

### CODE REVIEW

**Comment by BrunoDeBarros** [comment]
Thank you very much for this! :smile:

**Comment by BrunoDeBarros** [comment]
Note: `invoices:pancake_cannot_auto_charge` and `invoices:auto_charge_needs_pancake_cron_job` are still in English so I'm removing them.

**Comment by BrunoDeBarros** [comment]
Pancake automatically falls back to English when a translation can't be found, so you don't need to worry about it.

**Comment by mamarmite** [comment]
Excellent! I made another pull request to fix my forgettings:P
And thank you for fixing the Amount Due and Due Date :)

**Pull request merged**
