### PR TITLE
Modifications

### PR DESCRIPTION
**Pull request by ahouin**

### CODE REVIEW

**Comment by BrunoDeBarros** [comment]
I love that you keep updating the French translation, thank you for your help. :smile: Is this helping you, by the way? The way we do things. It means that you don't have to worry about the translations falling out of date or anything.

**Comment by ahouin** [comment]
Yes it's pretty convenient. Nice way to do it, it's so much easier. Keep the good work @BrunoDeBarros

**Comment by BrunoDeBarros** [comment]
By the way, I've added you as a collaborator to the repo so you don't have to go through me whenever you want to update stuff in the French translation. You can now commit to the repo yourself. :smile:

**Comment by ahouin** [comment]
Awesome news @BrunoDeBarros ! Thanks a lot!

**Pull request merged**
